version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tuic_app

  web:
    extends:
      service: app
    environment:
      - VIRTUAL_HOST=tuic.dev,*.tuic.dev
    networks:
      - default
      - nginx
    command: 'lein ring server'
    volumes:
      - '.:/app'
    depends_on:
      - mongo

  mongo:
    image: mongo

networks:
  nginx:
    external:
      name: nginx_default
